#!/usr/bin/env python3
"""Funciones utilitarias para el TUI."""

import math
import subprocess
from .config import DEFAULT_CONFIG


def temp_to_rgb(temp):
    """Convertir temperatura (Kelvin) a RGB aproximado para vista previa.
    
    Algoritmo basado en Tanner Helland.
    """
    temp = temp / 100
    
    # Calcular componente rojo
    if temp <= 66:
        r = 255
    else:
        r = temp - 60
        r = 329.698727446 * (r ** -0.1332047592)
    
    # Calcular componente verde
    if temp <= 66:
        g = temp
        g = 99.4708025861 * math.log(g) - 161.1195681661
    else:
        g = temp - 60
        g = 288.1221695283 * (g ** -0.0755148492)
    
    # Calcular componente azul
    if temp <= 10:
        b = 0
    elif temp >= 66:
        b = 255
    else:
        b = temp - 10
        b = 138.5177312231 * math.log(b) - 305.0447927307
    
    return int(max(0, min(255, r))), int(max(0, min(255, g))), int(max(0, min(255, b)))


def get_label_for_time(hour, minute):
    """Obtener etiqueta descriptiva para un horario."""
    total_minutes = hour * 60 + minute
    if 5 * 60 <= total_minutes < 12 * 60:
        return "Mañana"
    elif 12 * 60 <= total_minutes < 17 * 60:
        return "Tarde"
    elif 17 * 60 <= total_minutes < 21 * 60:
        return "Atardecer"
    elif 21 * 60 <= total_minutes < 24 * 60 or total_minutes < 5 * 60:
        return "Noche"
    else:
        return "Madrugada"


def read_gamma_file(filepath):
    """Leer configuración gamma desde archivo.

    Soporta dos formatos:
    1. hora minuto temperatura [etiqueta]
    2. hora minuto temperatura (formato original)

    Returns:
        list: Lista de horarios ordenados por hora.
    """
    schedules = []
    try:
        with open(filepath, 'r') as f:
            for line in f.read().splitlines():
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                parts = line.split()
                if len(parts) >= 3:  # hora minuto temperatura [etiqueta]
                    hour = int(parts[0])
                    minute = int(parts[1])
                    temp = float(parts[2])
                    # Etiqueta opcional (cuarta columna)
                    if len(parts) >= 4:
                        label = ' '.join(parts[3:])  # Unir palabras restantes
                    else:
                        label = get_label_for_time(hour, minute)
                    schedules.append({
                        'hour': hour,
                        'minute': minute,
                        'temp': temp,
                        'time_str': f"{hour:02d}:{minute:02d}",
                        'temp_str': f"{int(temp)}K",
                        'label': label
                    })
        schedules.sort(key=lambda x: x['hour'] * 60 + x['minute'])
    except FileNotFoundError:
        pass
    return schedules


def write_gamma_file(filepath, schedules):
    """Escribir configuración gamma a archivo.
    
    Formato: hora minuto temperatura [etiqueta]
    """
    import os
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, 'w') as f:
        f.write("# =============================================================================\n")
        f.write("# blugon-lite Gamma Configuration\n")
        f.write("# Generated by blugon-lite-tui\n")
        f.write("# Format: hour minute temperature [label]\n")
        f.write("# =============================================================================\n\n")
        for sched in schedules:
            # Escribir línea de datos con etiqueta opcional
            f.write(f"{sched['hour']} {sched['minute']} {int(sched['temp'])} {sched['label']}\n")


def get_default_schedules():
    """Obtener horarios por defecto desde configuración hardcodeada."""
    schedules = []
    for line in DEFAULT_CONFIG.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        parts = list(map(float, line.split()))
        if len(parts) == 3:
            hour, minute, temp = parts
            label = get_label_for_time(int(hour), int(minute))
            schedules.append({
                'hour': int(hour),
                'minute': int(minute),
                'temp': temp,
                'time_str': f"{int(hour):02d}:{int(minute):02d}",
                'temp_str': f"{int(temp)}K",
                'label': label
            })
    schedules.sort(key=lambda x: x['hour'] * 60 + x['minute'])
    return schedules


def is_daemon_running():
    """Verificar si el daemon de blugon-lite está en ejecución."""
    try:
        result = subprocess.run(['pgrep', '-f', 'blugon-lite.py'],
                              capture_output=True, text=True)
        return result.returncode == 0 and result.stdout.strip() != ''
    except:
        return False


def toggle_daemon():
    """Alternar estado del daemon de blugon-lite."""
    if is_daemon_running():
        subprocess.run(['pkill', '-f', 'blugon-lite.py'])
        return False
    else:
        subprocess.Popen(['nohup', 'blugon-lite', '-i', '120'],
                        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return True
