#!/usr/bin/env python3
"""blugon-lite-tui - Text User Interface for blugon-lite configuration using urwid."""

import urwid
import subprocess
import os
import sys
from configparser import ConfigParser
from io import StringIO

# Constants
CONFIG_DIR = os.environ.get('XDG_CONFIG_HOME', os.path.expanduser('~/.config')) + '/blugon'
CONFIG_FILE = CONFIG_DIR + '/gamma'
VERSION = '1.0.0-lite'

# Default configuration for fallback
DEFAULT_CONFIG = """# Default blugon-lite configuration
8 0 6500
17 0 4500
21 0 3000
0 0 2000
6 0 2500
"""


def read_gamma_file(filepath):
    """Read gamma configuration from file. Returns list of schedules."""
    schedules = []
    try:
        with open(filepath, 'r') as f:
            for line in f.read().splitlines():
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                parts = list(map(float, line.split()))
                if len(parts) == 3:  # hour minute temperature
                    hour, minute, temp = parts
                    schedules.append({
                        'hour': int(hour),
                        'minute': int(minute),
                        'temp': temp,
                        'time_str': f"{int(hour):02d}:{int(minute):02d}",
                        'temp_str': f"{int(temp)}K"
                    })
        schedules.sort(key=lambda x: x['hour'] * 60 + x['minute'])
    except FileNotFoundError:
        pass
    return schedules


def write_gamma_file(filepath, schedules):
    """Write gamma configuration to file."""
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, 'w') as f:
        f.write("# =============================================================================\n")
        f.write("# blugon-lite Gamma Configuration\n")
        f.write("# Generated by blugon-lite-tui\n")
        f.write("# Format: hour minute temperature (Kelvin)\n")
        f.write("# =============================================================================\n\n")
        for sched in schedules:
            f.write(f"# {sched['time_str']} - {sched['temp_str']}\n")
            f.write(f"{sched['hour']} {sched['minute']} {int(sched['temp'])}\n\n")


def get_default_schedules():
    """Get default schedules from hardcoded config."""
    schedules = []
    for line in DEFAULT_CONFIG.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        parts = list(map(float, line.split()))
        if len(parts) == 3:  # hour minute temperature
            hour, minute, temp = parts
            schedules.append({
                'hour': int(hour),
                'minute': int(minute),
                'temp': temp,
                'time_str': f"{int(hour):02d}:{int(minute):02d}",
                'temp_str': f"{int(temp)}K"
            })
    schedules.sort(key=lambda x: x['hour'] * 60 + x['minute'])
    return schedules


class ScheduleListBox(urwid.ListBox):
    """Custom ListBox for schedule items."""
    pass


class ScheduleItem(urwid.WidgetWrap):
    """Widget representing a single schedule item."""
    
    def __init__(self, schedule, index, on_select, on_delete):
        self.schedule = schedule
        self.index = index
        self.on_select = on_select
        self.on_delete = on_delete
        self._selected = False
        
        self.text = urwid.Text(f"  {schedule['time_str']}  {schedule['temp_str']:>8}")
        self.attr = urwid.AttrMap(self.text, 'schedule')
        super().__init__(self.attr)
    
    def selectable(self):
        return True
    
    def keypress(self, size, key):
        if key == 'enter':
            self.on_select(self.index)
            return None
        elif key == 'd':
            self.on_delete(self.index)
            return None
        return super().keypress(size, key)
    
    def set_selected(self, selected):
        self._selected = selected
        if selected:
            self.attr.set_attr_map({None: 'schedule_selected'})
        else:
            self.attr.set_attr_map({None: 'schedule'})


class BlugonLiteTUI:
    """Main TUI application class."""
    
    def __init__(self):
        self.schedules = []
        self.selected_index = 0
        self.modified = False
        self.unsaved_changes = False
        
        # Load configuration
        self.load_config()
        
        # Create main layout
        self.create_widgets()
        
        # Create main loop
        self.loop = urwid.MainLoop(
            self.main_frame,
            palette=self.palette(),
            unhandled_input=self.handle_input,
            handle_mouse=False
        )
    
    def palette(self):
        return [
            ('header', 'white', 'dark blue'),
            ('footer', 'white', 'dark gray'),
            ('schedule', 'light gray', 'default'),
            ('schedule_selected', 'black', 'light gray'),
            ('status', 'yellow', 'default'),
            ('error', 'light red', 'default'),
            ('success', 'light green', 'default'),
            ('button', 'black', 'light gray'),
            ('dialog', 'white', 'dark blue'),
        ]
    
    def load_config(self):
        """Load gamma configuration."""
        self.schedules = read_gamma_file(CONFIG_FILE)
        if not self.schedules:
            # Try system config
            system_config = '/usr/share/blugon-lite/configs/evening/gamma'
            self.schedules = read_gamma_file(system_config)
        if not self.schedules:
            # Use default
            self.schedules = get_default_schedules()
    
    def create_widgets(self):
        """Create main UI widgets."""
        # Header
        self.header = urwid.AttrMap(
            urwid.Text("  blugon-lite TUI - Configuration Editor", align='center'),
            'header'
        )

        # Instructions
        self.instructions = urwid.Text([
            "\n",
            ('status', "↑/↓"), " Navigate  ",
            ('status', "e"), " Edit  ",
            ('status', "a"), " Add  ",
            ('status', "d"), " Delete  ",
            ('status', "s"), " Save  ",
            ('status', "q"), " Quit  ",
            ('status', "h"), " Help"
        ])

        # Status line (create before refresh_schedule_list)
        self.status = urwid.AttrMap(
            urwid.Text(" Ready"),
            'status'
        )

        # Schedule list
        self.schedule_items = []
        self.refresh_schedule_list()

        self.schedule_walker = urwid.SimpleFocusListWalker(self.schedule_items)
        self.schedule_list = ScheduleListBox(self.schedule_walker)

        # Footer
        self.footer = urwid.AttrMap(
            urwid.Text(f"  Version: {VERSION}  |  Config: {CONFIG_FILE}", align='center'),
            'footer'
        )
        
        # Main content
        self.main_content = urwid.Pile([
            ('pack', self.instructions),
            ('weight', 1, urwid.AttrMap(self.schedule_list, 'default')),
            ('pack', self.status),
        ])
        
        # Main frame
        self.main_frame = urwid.Frame(
            self.main_content,
            header=self.header,
            footer=self.footer
        )
    
    def refresh_schedule_list(self):
        """Refresh the schedule list widget."""
        self.schedule_items.clear()
        for i, sched in enumerate(self.schedules):
            item = ScheduleItem(sched, i, self.edit_schedule, self.delete_schedule)
            if i == self.selected_index:
                item.set_selected(True)
            self.schedule_items.append(item)
        
        # Update status
        if self.unsaved_changes:
            self.status.original_widget.set_text(" (* Unsaved changes)")
        else:
            self.status.original_widget.set_text(" Ready")
    
    def handle_input(self, key):
        """Handle global keyboard input."""
        if key == 'q':
            if self.unsaved_changes:
                self.show_confirm_exit()
            else:
                raise urwid.ExitMainLoop()
        elif key == 's':
            self.save_config()
        elif key == 'a':
            self.add_schedule()
        elif key == 'h':
            self.show_help()
        elif key == 'up':
            if self.selected_index > 0:
                self.selected_index -= 1
                self.refresh_schedule_list()
        elif key == 'down':
            if self.selected_index < len(self.schedules) - 1:
                self.selected_index += 1
                self.refresh_schedule_list()
        elif key == 'e':
            if self.schedules:
                self.edit_schedule(self.selected_index)
    
    def show_message(self, message, style='status'):
        """Show a message in the status line."""
        self.status.original_widget.set_text(f" {message}")
        self.status.set_attr_map({None: style})
    
    def show_help(self):
        """Show help dialog."""
        help_text = [
            "blugon-lite TUI Help",
            "=" * 40,
            "",
            "Navigation:",
            "  ↑/↓     Move up/down in schedule list",
            "  Enter   Edit selected schedule",
            "",
            "Actions:",
            "  a       Add new schedule",
            "  d       Delete selected schedule",
            "  e       Edit selected schedule",
            "  s       Save changes",
            "  q       Quit",
            "  h       Show this help",
            "",
            "Format:",
            "  Each schedule entry defines a time and",
            "  color temperature (Kelvin).",
            "  blugon-lite interpolates between entries.",
            "",
            "Press any key to close help."
        ]
        
        body = urwid.Pile([urwid.Text(line) for line in help_text])
        box = urwid.LineBox(body, title="Help")
        overlay = urwid.Overlay(
            urwid.AttrMap(box, 'dialog'),
            self.main_frame,
            align='center',
            width=('relative', 60),
            valign='middle',
            height=('relative', 80),
            left=2,
            right=2,
            top=2,
            bottom=2
        )
        
        self.loop.widget = overlay
        self.loop.run()
        self.loop.widget = self.main_frame
    
    def show_confirm_exit(self):
        """Show confirm exit dialog."""
        body = urwid.Pile([
            urwid.Text("You have unsaved changes."),
            urwid.Text("Are you sure you want to quit?"),
            urwid.Divider(),
            urwid.Button("Yes", self.confirm_exit_yes),
            urwid.Button("No", self.confirm_exit_no),
        ])
        box = urwid.LineBox(body, title="Confirm Exit")
        overlay = urwid.Overlay(
            urwid.AttrMap(box, 'dialog'),
            self.main_frame,
            align='center',
            width=50,
            valign='middle',
            height=12,
        )
        
        self.loop.widget = overlay
        self.loop.run()
        self.loop.widget = self.main_frame
    
    def confirm_exit_yes(self, button):
        """Confirm exit."""
        raise urwid.ExitMainLoop()
    
    def confirm_exit_no(self, button):
        """Cancel exit."""
        self.loop.widget = self.main_frame
    
    def edit_schedule(self, index):
        """Edit a schedule entry."""
        if index < 0 or index >= len(self.schedules):
            return
        
        sched = self.schedules[index]
        
        # Create edit dialog
        hour_edit = urwid.Edit("Hour (0-23): ", str(sched['hour']))
        minute_edit = urwid.Edit("Minute (0-59): ", str(sched['minute']))
        temp_edit = urwid.Edit("Temperature (1000-20000K): ", str(int(sched['temp'])))
        
        body = urwid.Pile([
            urwid.Text(f"Edit Schedule Entry #{index + 1}"),
            urwid.Divider(),
            hour_edit,
            minute_edit,
            temp_edit,
            urwid.Divider(),
            urwid.Button("Save", lambda b: self.save_edit(index, hour_edit, minute_edit, temp_edit)),
            urwid.Button("Cancel", lambda b: self.cancel_edit()),
        ])
        
        box = urwid.LineBox(body, title="Edit Schedule")
        overlay = urwid.Overlay(
            urwid.AttrMap(box, 'dialog'),
            self.main_frame,
            align='center',
            width=50,
            valign='middle',
            height=14,
        )
        
        self.loop.widget = overlay
        self.loop.run()
        self.loop.widget = self.main_frame
    
    def save_edit(self, index, hour_edit, minute_edit, temp_edit):
        """Save edited schedule."""
        try:
            hour = int(hour_edit.edit_text)
            minute = int(minute_edit.edit_text)
            temp = int(temp_edit.edit_text)
            
            if not (0 <= hour <= 23):
                raise ValueError("Hour must be 0-23")
            if not (0 <= minute <= 59):
                raise ValueError("Minute must be 0-59")
            if not (1000 <= temp <= 20000):
                raise ValueError("Temperature must be 1000-20000")
            
            self.schedules[index] = {
                'hour': hour,
                'minute': minute,
                'temp': temp,
                'time_str': f"{hour:02d}:{minute:02d}",
                'temp_str': f"{temp}K"
            }
            self.schedules.sort(key=lambda x: x['hour'] * 60 + x['minute'])
            self.unsaved_changes = True
            self.refresh_schedule_list()
            self.show_message("Schedule updated", 'success')
        except ValueError as e:
            self.show_message(f"Error: {e}", 'error')
            return
        
        self.loop.widget = self.main_frame
    
    def cancel_edit(self, button):
        """Cancel edit."""
        self.loop.widget = self.main_frame
    
    def add_schedule(self):
        """Add a new schedule entry."""
        hour_edit = urwid.Edit("Hour (0-23): ", "12")
        minute_edit = urwid.Edit("Minute (0-59): ", "0")
        temp_edit = urwid.Edit("Temperature (1000-20000K): ", "6500")
        
        body = urwid.Pile([
            urwid.Text("Add New Schedule Entry"),
            urwid.Divider(),
            hour_edit,
            minute_edit,
            temp_edit,
            urwid.Divider(),
            urwid.Button("Add", lambda b: self.save_add(hour_edit, minute_edit, temp_edit)),
            urwid.Button("Cancel", lambda b: self.cancel_add()),
        ])
        
        box = urwid.LineBox(body, title="Add Schedule")
        overlay = urwid.Overlay(
            urwid.AttrMap(box, 'dialog'),
            self.main_frame,
            align='center',
            width=50,
            valign='middle',
            height=14,
        )
        
        self.loop.widget = overlay
        self.loop.run()
        self.loop.widget = self.main_frame
    
    def save_add(self, hour_edit, minute_edit, temp_edit):
        """Save new schedule."""
        try:
            hour = int(hour_edit.edit_text)
            minute = int(minute_edit.edit_text)
            temp = int(temp_edit.edit_text)
            
            if not (0 <= hour <= 23):
                raise ValueError("Hour must be 0-23")
            if not (0 <= minute <= 59):
                raise ValueError("Minute must be 0-59")
            if not (1000 <= temp <= 20000):
                raise ValueError("Temperature must be 1000-20000")
            
            self.schedules.append({
                'hour': hour,
                'minute': minute,
                'temp': temp,
                'time_str': f"{hour:02d}:{minute:02d}",
                'temp_str': f"{temp}K"
            })
            self.schedules.sort(key=lambda x: x['hour'] * 60 + x['minute'])
            self.unsaved_changes = True
            self.refresh_schedule_list()
            self.show_message("Schedule added", 'success')
        except ValueError as e:
            self.show_message(f"Error: {e}", 'error')
            return
        
        self.loop.widget = self.main_frame
    
    def cancel_add(self, button):
        """Cancel add."""
        self.loop.widget = self.main_frame
    
    def delete_schedule(self, index):
        """Delete a schedule entry."""
        if index < 0 or index >= len(self.schedules):
            return
        
        # Create confirm dialog
        sched = self.schedules[index]
        body = urwid.Pile([
            urwid.Text(f"Delete schedule {sched['time_str']} ({sched['temp_str']})?"),
            urwid.Divider(),
            urwid.Button("Yes", lambda b: self.confirm_delete(index)),
            urwid.Button("No", lambda b: self.cancel_delete()),
        ])
        
        box = urwid.LineBox(body, title="Confirm Delete")
        overlay = urwid.Overlay(
            urwid.AttrMap(box, 'dialog'),
            self.main_frame,
            align='center',
            width=50,
            valign='middle',
            height=10,
        )
        
        self.loop.widget = overlay
        self.loop.run()
        self.loop.widget = self.main_frame
    
    def confirm_delete(self, index):
        """Confirm delete."""
        del self.schedules[index]
        self.unsaved_changes = True
        if self.selected_index >= len(self.schedules):
            self.selected_index = max(0, len(self.schedules) - 1)
        self.refresh_schedule_list()
        self.show_message("Schedule deleted", 'success')
        self.loop.widget = self.main_frame
    
    def cancel_delete(self, button):
        """Cancel delete."""
        self.loop.widget = self.main_frame
    
    def save_config(self):
        """Save configuration to file."""
        try:
            write_gamma_file(CONFIG_FILE, self.schedules)
            self.unsaved_changes = False
            self.modified = True
            self.refresh_schedule_list()
            self.show_message(f"Saved to {CONFIG_FILE}", 'success')
        except Exception as e:
            self.show_message(f"Error saving: {e}", 'error')
    
    def run(self):
        """Run the TUI."""
        try:
            self.loop.run()
        except KeyboardInterrupt:
            pass
        
        if self.unsaved_changes and self.modified:
            print("Warning: You have unsaved changes.")


def main():
    """Main entry point."""
    print("Starting blugon-lite TUI...")
    app = BlugonLiteTUI()
    app.run()
    print("Goodbye!")


if __name__ == "__main__":
    main()
